const API_BASE_URL_DEVELOPMENT = 'https://localhost:7066';

const ENDPOINTS = {
    GET_ALL_ACTIVITIES: 'api/Activities',
    GET_ACTIVITY_BY_ID: 'api/Activities',
    CREATE_ACTIVITY: 'api/Activities',
    UPDATE_ACTIVITY: 'api/Activities',
    DELETE_ACTIVITY_BY_ID: 'api/Activities'
};

const development = {
    API_URL_GET_ALL_POSTS: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_ACTIVITIES}`,
    API_URL_GET_POST_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ACTIVITY_BY_ID}`,
    API_URL_CREATE_POST: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.CREATE_ACTIVITY}`,
    API_URL_UPDATE_POST: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.UPDATE_ACTIVITY}`,
    API_URL_DELETE_POST_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.DELETE_ACTIVITY_BY_ID}`
};

const Constants =  development;

export default Constants;
